# Question 1

In [0]:
import numpy as np

In [0]:
# a) Generate 100 sequences of 1,000 states.  

####################
# Setting up initial
# and transitional
# probability matrices
#####################

initial_probs = np.array([0.5, 0.2, 0.3])

transition_probs = np.array([[0.4,0.3,0.3],
                            [0.2,0.6,0.2],
                            [0.1,0.1,0.8]])

In [0]:
####################
# Generating 100
# sequences of 1,000
# states
####################
state_names = ['S1','S2','S3']
num_sequences = 100
num_states = 1000
sequence_list = list()
for j in range(0, num_sequences):
  state_list = list()
  for i in range(0, num_states):
    if i == 0:
      state_list.append(np.random.choice(state_names,p = initial_probs))
    else:
      if state_list[i-1] == 'S1':
        state_list.append(np.random.choice(state_names,p = transition_probs[0]))
      if state_list[i-1] == 'S2':
        state_list.append(np.random.choice(state_names,p = transition_probs[1]))
      if state_list[i-1] == 'S3':
        state_list.append(np.random.choice(state_names,p = transition_probs[2]))
  sequence_list.append(state_list)
  
    

In [0]:
###########################
# Output from sequence list
###########################
sequence_list[0][0:20]

['S1',
 'S1',
 'S3',
 'S3',
 'S3',
 'S1',
 'S1',
 'S1',
 'S2',
 'S3',
 'S3',
 'S3',
 'S3',
 'S3',
 'S2',
 'S2',
 'S3',
 'S3',
 'S3',
 'S3']

In [0]:
# b) Using the data generated in part a), estimate the initial and transitional probability matrices
# compare these matrices with the ones used to generate the data.

#####################
# Estimating initial 
# probailities 
#####################

est_initial_prob_list = np.array([sequence_list[i][0] for i in range(0,num_sequences)])

estimated_initial_probs = [len(est_initial_prob_list[est_initial_prob_list == 'S1'])/len(est_initial_prob_list),
                           len(est_initial_prob_list[est_initial_prob_list == 'S2'])/len(est_initial_prob_list),
                           len(est_initial_prob_list[est_initial_prob_list == 'S3'])/len(est_initial_prob_list)]
estimated_initial_probs

[0.49, 0.18, 0.33]

Estimated initial probabilities are similar to initial probabilities

In [0]:
#####################
# Estimating transitional 
# probailities 
#####################

count_matrix = np.zeros(shape =(3,3))

In [0]:
transitional_combos = [['S1','S1'],
                       ['S1','S2'],
                       ['S1','S3'],
                       ['S2','S1'],
                       ['S2','S2'],
                       ['S2','S3'],
                       ['S3','S1'],
                       ['S3','S2'],
                       ['S3','S3']]

for i in range(0,num_sequences):
  for j in range(0,num_states):
    if(sequence_list[i][j:j+2] == transitional_combos[0]):
      count_matrix[0][0] += 1
    if(sequence_list[i][j:j+2] == transitional_combos[1]):
      count_matrix[0][1] += 1
    if(sequence_list[i][j:j+2] == transitional_combos[2]):
      count_matrix[0][2] += 1
    if(sequence_list[i][j:j+2] == transitional_combos[3]):
      count_matrix[1][0] += 1
    if(sequence_list[i][j:j+2] == transitional_combos[4]):
      count_matrix[1][1] += 1 
    if(sequence_list[i][j:j+2] == transitional_combos[5]): 
      count_matrix[1][2] += 1
    if(sequence_list[i][j:j+2] == transitional_combos[6]): 
      count_matrix[2][0] += 1
    if(sequence_list[i][j:j+2] == transitional_combos[7]):
      count_matrix[2][1] += 1 
    if(sequence_list[i][j:j+2] == transitional_combos[8]): 
      count_matrix[2][2] += 1

In [0]:
count_matrix

array([[ 7415.,  5555.,  5405.],
       [ 5492., 16491.,  5564.],
       [ 5430.,  5521., 43027.]])

In [0]:
np.round([count_matrix[0]/sum(count_matrix)[0],
 count_matrix[1]/sum(count_matrix)[1],
 count_matrix[2]/sum(count_matrix)[2]],2)

array([[0.4 , 0.3 , 0.29],
       [0.2 , 0.6 , 0.2 ],
       [0.1 , 0.1 , 0.8 ]])

Estimated transitional probabilities are similar to transitional probabilities

In [0]:
# c) Repeat part (b) using hmmlearn package. You can select a suitable emission probability distri-
# bution from available options in hmmlearn. Report the differences in the computed values from part

In [0]:
pip install hmmlearn

     |████████████████████████████████| 368kB 4.8MB/s 


In [0]:
from hmmlearn import hmm
np.random.seed(1234)

In [0]:
# Code to build this model is adapted from the following webpage
#https://hmmlearn.readthedocs.io/en/latest/tutorial.html

#############################
# Building HMM model
#############################

model = hmm.GaussianHMM(n_components=3, covariance_type="full")
model.startprob_ = initial_probs
model.transmat_ = transition_probs
# I am not sure how the model means and covariances work, 
# I took what was provided in the tutorial link above and tested
# that out. 
model.means_ = np.array([[0.0, 0.0], [3.0, -3.0], [5.0, 10.0]])
# this makes sense because our states are independent 
model.covars_ = np.tile(np.identity(2), (3, 1, 1)) 

In [0]:
######################################
# calculating 100 sequences each with 
# 1000 states
######################################

hmm_model_list = list()
for i in range(0,num_sequences):
  X, Z = model.sample(1000)
  hmm_model_list.append(Z)

In [0]:
hmm_model_list[0][0:20]

array([2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
#####################
# Estimating initial 
# probailities 
#####################

est_hmm_initial_prob_list = np.array([hmm_model_list[i][0] for i in range(0,num_sequences)])

estimated_initial_probs = [len(est_hmm_initial_prob_list[est_hmm_initial_prob_list == 0])/len(est_hmm_initial_prob_list),
                           len(est_hmm_initial_prob_list[est_hmm_initial_prob_list == 1])/len(est_hmm_initial_prob_list),
                           len(est_hmm_initial_prob_list[est_hmm_initial_prob_list == 2])/len(est_hmm_initial_prob_list)]
estimated_initial_probs

[0.55, 0.22, 0.23]

Similar to our intial probability matrix but the third state value is only .23, compared to .3

In [0]:
#####################
# Estimating transitional 
# probailities 
#####################

count_hmm_matrix = np.zeros(shape =(3,3))

In [0]:
transitional_hmm_combos = [[0,0],
                       [0,1],
                       [0,2],
                       [1,0],
                       [1,1],
                       [1,2],
                       [2,0],
                       [2,1],
                       [2,2]]

for i in range(0,num_sequences):
  for j in range(0,num_states):
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[0])):
      count_hmm_matrix[0][0] += 1
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[1])):
      count_hmm_matrix[0][1] += 1
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[2])):
      count_hmm_matrix[0][2] += 1
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[3])):
      count_hmm_matrix[1][0] += 1
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[4])):
      count_hmm_matrix[1][1] += 1 
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[5])): 
      count_hmm_matrix[1][2] += 1
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[6])): 
      count_hmm_matrix[2][0] += 1
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[7])):
      count_hmm_matrix[2][1] += 1 
    if(all(hmm_model_list[i][j:j+2] == transitional_hmm_combos[8])): 
      count_hmm_matrix[2][2] += 1



In [0]:
np.round([count_hmm_matrix[0]/sum(count_hmm_matrix)[0],
 count_hmm_matrix[1]/sum(count_hmm_matrix)[1],
 count_hmm_matrix[2]/sum(count_hmm_matrix)[2]],2)

array([[0.4, 0.3, 0.3],
       [0.2, 0.6, 0.2],
       [0.1, 0.1, 0.8]])

Estimated transitional probabilities are similar to the initial transitional probability matrix provided in the question.